### ISSUE TITLE
按照官网操作，运行提示错误

### ISSUE THREAD

**Issue by bromiao** [shuidi-fed/vapperjs.org#7]
![image](https://user-images.githubusercontent.com/19767083/68989964-49813380-0888-11ea-88c0-879e881ac745.png)
好像是源码路径问题，该怎么解决呢

**Comment by HcySunYang** [comment]
这确实是兼容的问题，在 @vapper/core 的补丁版本 `0.13.1` 中已经得到修复，安装最新版即可。另外，下次记得去 https://github.com/shuidi-fed/vapper 这个仓库提 issue 哦。
